services:
  postgres_cadastro:
   container_name: postgres_cadastro_ifood
   image: postgres:16.2
   environment:
    POSTGRES_USER: cadastro
    POSTGRES_PASSWORD: cadastro
   ports:
    - "5432:5432"
  keycloak_ifood:
    container_name: keycloak_ifood
    image: quay.io/keycloak/keycloak:25.0.6
    environment: 
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command:
      [ "start-dev"]
    ports:
      - "8180:8080"